import Head from "next/head";
import { UserButton } from "@clerk/nextjs";
import { useUser } from "@clerk/nextjs";
import dayjs from "dayjs";
import relativeTime from 'dayjs/plugin/relativeTime'

import { RouterOutputs, api } from "~/utils/api";

dayjs.extend(relativeTime)

const CreatePostWizard = () => {
  const { user } = useUser();

  console.log("user", user);

  if (!user) return null;

  return (
    <div className="flex w-full gap-4">
      <img
        src={user.imageUrl}
        alt="profile image"
        className="h-12 w-12 rounded-full"
      />
      <input
        placeholder="Type some emojis!"
        className="grow bg-transparent outline-none"
      />
    </div>
  );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div
      className="flex items-center border-b border-slate-400 p-8"
      key={post.id}
    >
      <img
        src={author.profilePicture}
        alt="author profil picture"
        className="mr-4 h-12 w-12 rounded-full"
      />
      <div className="flex flex-col">
        <div className="flex text-slate-300 gap-2">
          <span className="font-bold">{`@${author.name}`}</span>
          <span>{` • ${dayjs(post.createdAt).fromNow()}`}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  );
};

export default function Home() {
  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Something went wrong...</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex h-full w-full justify-center">
        <div className="flex h-full w-full justify-end border-b border-slate-400 p-4 md:max-w-2xl">
          <UserButton afterSignOutUrl="/" />
        </div>
      </header>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="h-auto w-full border-b border-slate-400 p-4">
            <CreatePostWizard />
          </div>
          <div className="flex flex-col">
            {data?.map((fullPost) => (
              <PostView {...fullPost} key={fullPost.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
